<div  class="bar">HIGHLIGHTS OF QUALIFICATIONS</div>
<div class="highlights">
  <ul>
    <?php

    // no frills
    team_player();
    manager();
    communicator();
    multicultural(); 
    learner();
    hard_worker();
    // programmer();
    // organizer();
    // analyst();
    // strategist();
    
    // problem_solver();
    
    // listener();
    // 
    // editor();
    
    // translator();

    /*---------------------------------------------
    // CANTIRE IT Infrastructure Leadership Program
    manager();
    programmer();
    // organizer();
    analyst();
    // strategist();
    communicator();    
    // problem_solver();
    team_player();
    // listener();
    // multicultural();
    // editor();
    learner();
    // translator();
    -----------------------------*/
    
    /*
    // SyncBASE
    software_developer2();
    programmer(); //
    // manager();
    // organizer();
    analyst();
    // strategist();
       
    // problem_solver();
    team_player(); //
    // listener();
    // multicultural();
    // editor();
    learner();
    communicator(); 
    // translator();
    */
    
    // PALOMINO - 141003
    // seneca_student();
    // software_developer();
    // web_designer();
    // analyst2();
    // communicator2();
    // programmer();
    // manager();
    // organizer();
    // analyst();
    // strategist();
    // communicator();    
    // problem_solver();
    // team_player();
    // listener();
    // multicultural();
    // editor();
    // learner();
    // translator();
    
    /*------------------
    // 141003fr IBM
    programmer();
    manager();
    //organizer();
    analyst();
    strategist();
    communicator();    
    //problem_solver();
    team_player();
    //listener();
    multicultural();
    //editor();
    //learner();
    //translator();
    -------------------*/
    /*--------------------
    programmer();
    manager();
    organizer();
    analyst();
    strategist();
    communicator();    
    problem_solver();
    team_player();
    listener();
    multicultural();
    editor();
    learner();
    translator();
    ----------------------*/
    ?>
  </ul>
</div>