<div  class="bar">HIGHLIGHTS OF QUALIFICATIONS</div>
<div class="highlights">
  <ul>
    <?php
    /*
    // IKEA - Kitchen Planning Sales
    customer_service();
    manager();
    programmer();
    analyst();
    communicator();
    teacher();
    learner();
    // listener();
    // multicultural(); 
    // no frills
    // team_player();

    
    // hard_worker();
    // 
    // organizer();
    // 
    // strategist();
    
    // problem_solver();
    
    // 
    // 
    // editor();
    
    // translator();
    */
    /*---------------------------------------------
    // CANTIRE IT Infrastructure Leadership Program
    manager();
    programmer();
    // organizer();
    analyst();
    // strategist();
    communicator();    
    // problem_solver();
    team_player();
    // listener();
    // multicultural();
    // editor();
    learner();
    // translator();
    -----------------------------*/
    
    
    // SyncBASE
    software_developer3();
    programmer2();
    // manager();
    // organizer();
    analyst3();
    cs_dev();
    mysql_savvy();
    communicator2();

    // strategist();
       
    // problem_solver();
    // team_player(); //
    // listener();
    // multicultural();
    // editor();
    // learner();
     
    // translator();
    
    
    // PALOMINO - 141003
    // seneca_student();
    // software_developer();
    // web_designer();
    // analyst2();
    // communicator2();
    // programmer();
    // manager();
    // organizer();
    // analyst();
    // strategist();
    // communicator();    
    // problem_solver();
    // team_player();
    // listener();
    // multicultural();
    // editor();
    // learner();
    // translator();
    
    /*------------------
    // 141003fr IBM
    programmer();
    manager();
    //organizer();
    analyst();
    strategist();
    communicator();    
    //problem_solver();
    team_player();
    //listener();
    multicultural();
    //editor();
    //learner();
    //translator();
    -------------------*/
    /*--------------------
    programmer();
    manager();
    organizer();
    analyst();
    strategist();
    communicator();    
    problem_solver();
    team_player();
    listener();
    multicultural();
    editor();
    learner();
    translator();
    ----------------------*/
    ?>
  </ul>
</div>