<div  class="bar">HIGHLIGHTS OF SKILLS AND QUALIFICATIONS</div>
<div class="highlights">
  <ul>
    <?php
    // CANTIRE IT Infrastructure Leadership Program
    manager();
    programmer();
    // organizer();
    analyst();
    // strategist();
    communicator();    
    // problem_solver();
    team_player();
    // listener();
    // multicultural();
    // editor();
    learner();
    // translator();
    /*---------------------------
    // SyncBASE
    programmer(); //
    // manager();
    // organizer();
    analyst();
    // strategist();
       
    // problem_solver();
    team_player(); //
    // listener();
    // multicultural();
    // editor();
    learner();
    communicator(); 
    // translator();
    -------------------------------*/
    /*---------------------------
    // PALOMINO - 141003
    programmer();
    // manager();
    // organizer();
    analyst();
    strategist();
    communicator();    
    // problem_solver();
    team_player();
    // listener();
    multicultural();
    // editor();
    // learner();
    // translator();
    -------------------*/
    /*------------------
    // 141003fr IBM
    programmer();
    manager();
    //organizer();
    analyst();
    strategist();
    communicator();    
    //problem_solver();
    team_player();
    //listener();
    multicultural();
    //editor();
    //learner();
    //translator();
    -------------------*/
    /*--------------------
    programmer();
    manager();
    organizer();
    analyst();
    strategist();
    communicator();    
    problem_solver();
    team_player();
    listener();
    multicultural();
    editor();
    learner();
    translator();
    ----------------------*/
    ?>
  </ul>
</div>