<?php
/*
  function bla(){
    $x = "bla";
    print $x;
  }

*/
//==========================================================================
// ADDRESS
//==========================================================================
  
//==========================================================================
// OBJECTIVE STATEMENT
//==========================================================================

//==========================================================================
// PROJECTS
//==========================================================================
  
//==========================================================================
// HIGHLIGHTED SKILLS
//==========================================================================
  
  
  //=== CUSTOMIZED AGGREGATES =======================================

  function dollarama(){
    hard_worker();
    team_player();
    multicultural();
    communicator();
    listener();
  }
  function it(){
    programmer();
    analyst();
    learner();
    team_player();
    communicator();
    manager();
  }
  function cantire(){
    team_player();
    manager();                
    communicator();
    multicultural();
    listener();
    //hard_worker();
  }
  function ibm_it_hl(){
    manager();
    programmer();
    analyst();
    strategist();
    communicator();
  }
  function all_skills(){
    programmer();
    manager();
    organizer();
    analyst();
    strategist();
    communicator();    
    problem_solver();
    team_player();
    listener();
    multicultural();
    editor();
    learner();
    translator();
  }
  // 141003fr
  function IBM_skills(){
    programmer();
    manager();
    organizer();
    analyst();
    strategist();
    communicator();    
    problem_solver();
    team_player();
    listener();
    multicultural();
    editor();
    learner();
    translator();
  }

//==========================================================================
// TECHNICAL SKILLS
//==========================================================================
  
//==========================================================================
// EDUCATION
//==========================================================================
  // education: Arts school
    
  // education: CELTA

  // education: Herzen

  // education: Seneca

  // education: Seneca projects

//==========================================================================
// WORK EXPERIENCE
//==========================================================================
  // work experience: C&T

    function cat_pos_name(){
      $x = "Translator";
      print $x;
    }
    function cat_name(){
      $x = "The C&T Publishing Company, Sochi, Russia";
      print $x;
    }
    function cat_time(){
      $x = "Sep 1995 - Dec 1996";
      print $x;
    }

  // work experience: C&T (achievements)

    function cat_translate(){
      $x = "Greatly improved the international correspondence "
              . "and interpreted at multiple meetings";
      print "<li>" . $x . "</li>";
    }

  // work experience: School of Tomorrow

  // work experience: School of Tomorrow (achievements)

  // work experience: AdlerKurort

  // work experience: AdlerKurort (achievements)

  // work experience: CCS

  // work experience: CCS (achievements)

  // work experience: Blagoveshchensk
  
  // work experience: China

  // work experience: China (achievements)
  
  // work experience: CDOT

  // work experience: CDOT (achievements)

//==========================================================================
// ACHIEVEMENTS
//==========================================================================

  function bilingual(){
    $x = "Raised my children bilingual (English and Russian)";
    print "<li>" . $x . "</li>";
  }
  function curriculum(){
    $x = "Developed my own Teach-Yourself-English curriculum";
    print "<li>" . $x . "</li>";
  }

//==========================================================================
// HOBBIES AND INTERESTS
//==========================================================================

  function linguist(){ 
    $x = "Linguistics and languages (Chinese, Latin, Hebrew)";
    print "<li>" . $x . "</li>";
  }

  function musician(){
    $x = "Music (drums, guitar)";
    print "<li>" . $x . "</li>";
  }

  function web_wizard(){
    $x = "Aspire to become a wizard in web application development";
    print "<li>" . $x . "</li>";
  }
  function almond(){
    $x = "Almond: system to store web links - developing since 2013 "
            . "using JavaScript and Node.js";
    print "<li>" . $x . "</li>";
  }
  function language_software(){
    $x = "Developing scripts for an application to help learn "
            . "language vocabulary";
    print "<li>" . $x . "</li>";
  }
  
  function autotransl(){
    $x = "Interested in automated translation";
    print "<li>" . $x . "</li>";
  }


//==========================================================================
// VOLUNTEER
//==========================================================================

  function lwc(){
    $x = "Youth services manager: effectively and knowledgeably supervised "
            . "a staff of 8 teachers at a church Youth Department. "
            . "On departure, was repeatedly asked to return because of "
            . "good performance";
    print "<li>" . $x . "</li>";
  }
  function scenic_designer(){
    $x = "Scenic designer: designed and manufactured theatrical scenery "
            . "for a community theater production";
    print "<li>" . $x . "</li>";
  }
  function humaid(){
    $x = "Humanitarian aid distribution: assisted in the community during "
            . "the economic crisis in the country in late 1990";
    print "<li>" . $x . "</li>";
  }