<div class="bar">PROJECTS</div>
<div class="highlights">
  <ul>

<?php

  function android_subaru(){
    $x = "Database-driven Android application for drivers to keep track of "
       . "gas purchases by gas station";
    print "<li>" . $x. "</li>";
  }

  function cs_class_cancellations(){
    $x = "Database-driven web application in C# using ASP.NET MVC4 in "
       . "Visual Studio that keeps records of faculty and students "
       . "and notifies them of classes' cancellations";
    print "<li>" . $x. "</li>";
  }

  function db_drugstore(){
    $x = "Physical and conceptual database design for a system according "
       . "to a company's specification";
    print "<li>" . $x. "</li>";
  }

  function cobol_seneca_construction(){
    $x = "COBOL application that maintains construction projects";
    print "<li>" . $x. "</li>";
  }  

  function JS_mamapizza(){
    $x = "Graphic interface using JavaScript, HTML5 and CSS "
       . "for an online store that sells pizza";
    print "<li>" . $x. "</li>";
  }

  function JS_togetherjs(){
    $x = "Localization solution for a Mozilla project "
       . "that enables several users to remotely collaborate in real time "
       . "on the same project online";
    print "<li>" . $x. "</li>";
  }

  function JS_webmaker(){
    $x = "Localization solution for a Mozilla project that is a squite of "
       . "tools designed to teach creation of content for the web";
    print "<li>" . $x. "</li>";
  }

  function php_surplus(){
    $x = "Website using Linux, Apache, MySQL, PHP for an online store "
            . "that sells army surplus goods";
    print "<li>" . $x. "</li>";
  }

  function php_tarboz(){
    $x = "Large web application using Apache, MySQL, PHP that "
            . "is an online database for storing international winged phrases";
    print "<li>" . $x. "</li>";
  }

    android_subaru();
    cobol_seneca_construction();
    cs_class_cancellations();
    db_drugstore();
    JS_mamapizza();
    JS_togetherjs();
    JS_webmaker();
    php_surplus();
    php_tarboz();
    
?>
  </ul>
</div>
