<div id="goal">
<?php
  function objective(){
    $x = "Career goal: software developer";
    // $x = "GOAL: .NET DEVELOPER";
    // $x = "CAREER GOAL: WEB DEVELOPER";
    // $x = "GOAL: .Net Developer (Toronto) (#279941)";
    // $x = "GOAL: Kitchen Planning Sales";
    // $x = "GOAL: Participation in the IT Infrastructure Leadership Program";
    // $x = "GOAL: Richard's No Frills Store Team Member";
    // $x = "GOAL: Web Application Developer";
    // $x = "GOAL: Web Application Developer";
    // $x = "OBJECTIVE: CANADIAN TIRE STORE TEAM MEMBER";
    // $x = "OBJECTIVE: Entry-Level Business Consultant/ IT Specialist"; // IBM - Nova Scotia
    // $x = "OBJECTIVE: Software Developer";
    // $x = "Objective: to obtain a retail position";
    // $x = "OBJECTIVE: Web Developer/Software Engineer";
    print $x;
  }
  objective();

?>

</div>