<!-- <div class="bar">TECHNICAL SKILLS</div>
      <div id="table">

          <div>
            <div>Operating Systems</div>
            <td><?php print print_array($ar_OS); ?></div>
          </div>

          <div>
            <div>Programming</div>
            <td><?php print print_array($ar_prog); ?></div>
          </div>

          <div>
            <div>Database</div>
            <td><?php print print_array($ar_db); ?></div>
          </div>

          <div>
            <div>Tools</div>
            <td><?php print print_array($ar_tools); ?></div>
          </div>
          
      </div> -->

  <div class="bar">TECHNICAL SKILLS</div>
      <div class="table">

          <div>
            <div class="tr_title">Operating Systems</div>
            <div class="tr_value"><?php print print_array($ar_OS); ?></div>
          </div>

          <div>
            <div class="tr_title">Programming</div>
            <div class="tr_value"><?php print print_array($ar_prog); ?></div>
          </div>

          <div>
            <div class="tr_title">Database</div>
            <div class="tr_value"><?php print print_array($ar_db); ?></div>
          </div>

          <div>
            <div class="tr_title">Tools</div>
            <div class="tr_value"><?php print print_array($ar_tools); ?></div>
          </div>
          
      </div>