<!-- <div class="bar">TECHNICAL SKILLS</div>
      <div id="table">

          <div>
            <div>Operating Systems</div>
            <td><?php print print_array($ar_OS); ?></div>
          </div>

          <div>
            <div>Programming</div>
            <td><?php print print_array($ar_prog); ?></div>
          </div>

          <div>
            <div>Database</div>
            <td><?php print print_array($ar_db); ?></div>
          </div>

          <div>
            <div>Tools</div>
            <td><?php print print_array($ar_tools); ?></div>
          </div>
          
      </div> -->

  <div class="bar">TECHNICAL SKILLS</div>
      <table>

          <tr>
            <td class="tr_title">Operating Systems</td>
            <td class="tr_value"><?php print print_array($ar_OS); ?></td>
          </tr>

          <tr>
            <td class="tr_title">Programming</td>
            <td class="tr_value"><?php print print_array($ar_prog); ?></td>
          </div>

          <tr>
            <td class="tr_title">Database</td>
            <td class="tr_value"><?php print print_array($ar_db); ?></td>
          </div>

          <tr>
            <td class="tr_title">Tools</td>
            <td class="tr_value"><?php print print_array($ar_tools); ?></td>
          </div>
          
      </table>